"use strict";
exports.__esModule = true;
var jsondiffer_1 = require("../src/jsondiffer");
var coffee = { color: { color1: 'black', color2: 'brown' }, special: true };
var oil = { color: { color1: 'red', color2: 'blue' }, special2: false };
var treewalkerjs = new jsondiffer_1.JsonDiffer();
var diff = treewalkerjs.getDiff(coffee, oil);
console.log('coffee', coffee);
console.log('oil', oil);
console.log('diff', JSON.stringify(diff));
