name: CD

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Node environment
        uses: actions/setup-node@v6
        with:
          node-version: '24.15.0'
          cache: 'yarn'
          cache-dependency-path: |
            .yarn
            yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn nx run-many --target=build

      - name: Lint
        run: yarn nx run-many --target=lint

      - name: Type check
        run: yarn nx run-many --target=type-check

      - name: Test
        run: yarn nx run-many --target=test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v6
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
