name: Deploy to S3
on:
  push:
    tags:
      - 'json-difference-[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'yarn'
          cache-dependency-path: |
            .yarn
            yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: |
          yarn nx run-many --target=build-to-s3 --projects=json-difference

      - name: Deploy Json Difference to Amazon S3 🚀
        uses: reggionick/s3-deploy@v4
        with:
          folder: libs/json-difference/dist.browser-s3
          bucket: ${{ secrets.AWS_S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}
          delete-removed: false
          no-cache: true
          private: true
          files-to-include: '{.*/**,**}'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
