name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node environment
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.0'
          cache: 'yarn'
          cache-dependency-path: |
            .yarn
            yarn.lock

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Check types
        run: yarn check-types

      - name: Test
        run: yarn test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Build
        run: yarn build
